## **0. Tải bộ dữ liệu**
**Lưu ý:** Nếu bạn không thể sử dụng lệnh gdown để tải bộ dữ liệu vì bị giới hạn số lượt tải, hãy tải bộ dữ liệu thử công và upload lên google drive của mình. Sau đó, sử dụng lệnh dưới đây để copy file dữ liệu vào colab:
```python
from google.colab import drive

drive.mount('/content/drive')
!cp /path/to/dataset/on/your/drive .
```

In [ ]:
# https://drive.google.com/file/d/11fjFxxa2RfoLCJUQ_OSTm3GfMZHVy8Gy/view?usp=sharing
!gdown --id 11fjFxxa2RfoLCJUQ_OSTm3GfMZHVy8Gy

Downloading...
From: https://drive.google.com/uc?id=136oQPFJqG0vugwm0oAOU9IxwJN0zT54K
To: /content/Pokemon.csv
100% 44.0k/44.0k [00:00<00:00, 87.1MB/s]

## **1. Import thư viện và load dataset**

In [ ]:
import pandas as pd
import numpy as np

DATASET_PATH = '/content/Pokemon.csv'
data = pd.read_csv(DATASET_PATH)

In [ ]:
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

## **3. Đọc dữ liệu đứng đầu**

In [ ]:
data.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

## **4. Đọc dữ liệu đứng cuối**

In [ ]:
data.tail(8)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

## **5. Lấy tên cột (headers)**

In [ ]:
print(data.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

## **6. Đọc một cột cụ thể**

In [ ]:
print(data[['Name']].head())
print('\n')
print(data[['Name', 'Total', 'Attack']][:10:2])

                    Name
0              Bulbasaur
1                Ivysaur
2               Venusaur
3  VenusaurMega Venusaur
4             Charmander


                        Name  Total  Attack
0                  Bulbasaur    318      49
2                   Venusaur    525      82
4                 Charmander    309      52
6                  Charizard    534      84
8  CharizardMega Charizard Y    634     104

## **7. Đọc một hàng cụ thể**

In [ ]:
data.iloc[[3]]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False

In [ ]:
data.iloc[[3,6]]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False

In [ ]:
data.iloc[3:5]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [ ]:
data.loc[data['Legendary'] == True].head(2)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
156,144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True
157,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True

## **8. Đọc giá trị trong một hàng**

In [ ]:
data.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [ ]:
data.iloc[3,4]

625

In [ ]:
data.loc[data['Attack'] == 49, ['Name']]

          Name
0    Bulbasaur
166  Chikorita
506    Finneon

## **9. Lấy thông tin thống kê của bảng dữ liệu**

In [ ]:
data.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

## **10. Sắp xếp bảng dữ liệu theo giá trị của cột**

In [ ]:
data.sort_values('Type 1').head(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
600,540,Sewaddle,Bug,Grass,310,45,53,70,40,60,42,5,False
136,127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,1,False
457,412,Burmy,Bug,NaN,224,40,29,45,29,45,36,4,False

In [ ]:
data.sort_values('Type 1', ascending=False).head(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
371,339,Barboach,Water,Ground,288,50,48,43,46,41,60,3,False
97,90,Shellder,Water,NaN,305,30,65,100,45,25,40,1,False
240,222,Corsola,Water,Rock,380,55,55,85,65,85,35,2,False

In [ ]:
data.sort_values(['Type 1', 'HP'], ascending=[1, 0]).head(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,515,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,550,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,500,80,125,75,40,95,85,2,False

## **11. Thay đổi thông tin bảng dữ liệu**

In [ ]:
data.head(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False

In [ ]:
data = data.drop(columns=['Total'])
data.head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False

In [ ]:
data['Total'] = data['Attack'] + data['Defense'] + data['HP']
data.head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,143
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,185
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,245

## **12. Sắp xếp lại thứ tự các cột**

In [ ]:
data[['Name', 'Total', 'Attack', 'Speed']].head()

                    Name  Total  Attack  Speed
0              Bulbasaur    143      49     45
1                Ivysaur    185      62     60
2               Venusaur    245      82     80
3  VenusaurMega Venusaur    303     100     80
4             Charmander    134      52     65

In [ ]:
cols = list(data.columns.values)
print(cols)

['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Total']

In [ ]:
data[cols[0:4] + [cols[-1]] + cols[4:-1]].head(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,143,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,185,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,245,80,82,83,100,100,80,1,False

## **13. Lưu bảng dữ liệu mới**

In [ ]:
data.to_csv('modified.csv')

In [ ]:
data.to_excel('modified.xlsx', index = False)

In [ ]:
data.to_csv('modified_tab.csv', sep='\t')

## **14. Tìm kiếm các sample thỏa mãn điều kiện (filtering)**

In [ ]:
data.loc[(data['Type 1'] == 'Grass') & (data['Type 2'] == 'Poison')].head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,143
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,185
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,245

In [ ]:
data.loc[(data['Type 1'] == 'Grass') | (data['Type 2'] == 'Poison')][0::10].loc[data['HP'] > 50].head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False,240
101,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False,185
197,182,Bellossom,Grass,NaN,75,80,95,90,100,50,2,False,250

## **15. Filtering bằng regex**

In [ ]:
import re

In [ ]:
data.loc[data['Name'].str.contains('Mega')].head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,303
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,319
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,260

In [ ]:
data.loc[data['Type 1'].str.contains('Fire|grass', regex=True)].head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,134
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,180
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False,240

In [ ]:
data.loc[data['Type 1'].str.contains('fire|grass', flags=re.I, regex=True)].head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,143
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,185
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,245

In [ ]:
data.loc[data['Name'].str.contains('pi[a-z]*', flags=re.I, regex=True)].head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
13,10,Caterpie,Bug,NaN,45,30,35,20,20,45,1,False,110
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,125
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,178

In [ ]:
data.loc[data['Name'].str.contains('^pi[a-z]*', flags=re.I, regex=True)].head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,125
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,178
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False,238

In [ ]:
data.loc[data['Name'].str.contains('^pi.*', flags=re.I, regex=True)].head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,125
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,178
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False,238

## **16. Reset lại chỉ mục bảng dữ liệu**

In [ ]:
new_data = data.loc[(data['Type 1'] == 'Grass') | (data['Type 2'] == 'Poison')][0::10].loc[data['HP'] > 50].head(3)
new_data

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False,240
101,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False,185
197,182,Bellossom,Grass,NaN,75,80,95,90,100,50,2,False,250

In [ ]:
new_data = new_data.reset_index()
new_data

,index,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False,240
1,101,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False,185
2,197,182,Bellossom,Grass,NaN,75,80,95,90,100,50,2,False,250

In [ ]:
new_data = new_data.reset_index(drop=True)
new_data

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False,240
1,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False,185
2,182,Bellossom,Grass,NaN,75,80,95,90,100,50,2,False,250

In [ ]:
new_data.reset_index(drop=True, inplace = True)
new_data

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False,240
1,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False,185
2,182,Bellossom,Grass,NaN,75,80,95,90,100,50,2,False,250

## **17. Groupby**

In [ ]:
data.groupby(['Type 1']).mean().sort_values('Defense', ascending=False).head(10)

<ipython-input-53-90d84ee3bc80>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data.groupby(['Type 1']).mean().sort_values('Defense', ascending=False).head(10)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Type 1,,,,,,,,,,
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148,284.296296
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909,259.022727
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000,281.812500
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000,254.375000
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500,219.406250
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714,219.160714
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333,216.166667
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857,211.285714
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000,198.579710
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516,225.419355

In [ ]:
data.groupby(['Type 1', 'Type 2']).count()

                  #  Name  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
Type 1 Type 2
Bug    Electric   2     2   2       2        2        2        2      2
       Fighting   2     2   2       2        2        2        2      2
       Fire       2     2   2       2        2        2        2      2
       Flying    14    14  14      14       14       14       14     14
       Ghost      1     1   1       1        1        1        1      1
...              ..   ...  ..     ...      ...      ...      ...    ...
Water  Ice        3     3   3       3        3        3        3      3
       Poison     3     3   3       3        3        3        3      3
       Psychic    5     5   5       5        5        5        5      5
       Rock       4     4   4       4        4        4        4      4
       Steel      1     1   1       1        1        1        1      1

                 Generation  Legendary  Total
Type 1 Type 2
Bug    Electric           2          2      2
       Fighting           2          2      2
       Fire               2          2      2
       Flying            14         14     14
       Ghost              1          1      1
...                     ...        ...    ...
Water  Ice                3          3      3
       Poison             3          3      3
       Psychic            5          5      5
       Rock               4          4      4
       Steel              1          1      1

[136 rows x 11 columns]

In [ ]:
df = data.groupby(['Type 1'])['Attack', 'Defense'].apply(lambda x: np.sum(x)/len(x))
df.head(3)

<ipython-input-77-dcc0a50d3102>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df = data.groupby(['Type 1'])['Attack', 'Defense'].apply(lambda x: np.sum(x)/len(x))

            Attack    Defense
Type 1
Bug      70.971014  70.724638
Dark     88.387097  70.225806
Dragon  112.125000  86.375000

In [ ]:
df = data.groupby(['Type 1']).agg({'Attack': 'mean',
                                   'Defense': 'sum',
                                   'Speed': lambda x: len(x)})
df.head(3)

            Attack  Defense  Speed
Type 1
Bug      70.971014     4880     69
Dark     88.387097     2177     31
Dragon  112.125000     2764     32

## **Quiz**

In [ ]:
# 1
df = pd.read_csv('/content/Pokemon.csv')

In [ ]:
# 2
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [ ]:
# 3
df.tail(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [ ]:
# 4
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [ ]:
# 5
sr = df.iloc[10:16]
sr

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False
15,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False

In [ ]:
# 6
sr = df.iloc[50]
sr

#                    45
Name          Vileplume
Type 1            Grass
Type 2           Poison
Total               490
HP                   75
Attack               80
Defense              85
Sp. Atk             110
Sp. Def              90
Speed                50
Generation            1
Legendary         False
Name: 50, dtype: object

In [ ]:
# 7
grass_pokemon = df[df['Type 1'] == 'Grass']
grass_pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,313,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,405,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,530,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False

In [ ]:
# 8
high_hp_pokemon = df[df['HP'] > 100]
high_hp_pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
44,39,Jigglypuff,Normal,Fairy,270,115,45,20,45,25,20,1,False
45,40,Wigglytuff,Normal,Fairy,435,140,70,45,85,50,45,1,False
96,89,Muk,Poison,NaN,500,105,105,75,65,100,50,1,False
120,112,Rhydon,Ground,Rock,485,105,130,120,45,45,40,1,False
121,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
753,683,Aromatisse,Fairy,NaN,462,101,72,72,99,89,29,6,False
769,699,Aurorus,Rock,Ice,521,123,77,72,99,92,58,6,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True

In [ ]:
# 9
chu_pokemon = df[df['Name'].str.contains('chu', case=False)]
chu_pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
31,26,Raichu,Electric,NaN,485,60,90,55,90,80,110,1,False
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False
257,238,Smoochum,Ice,Psychic,305,45,30,15,85,65,65,2,False

In [ ]:
# 10
sorted_df = df.sort_values(by='Attack', ascending=False)
sorted_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
424,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False
121,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False
488,440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False

In [ ]:
# 11
df_reset = sorted_df.reset_index(drop=True)
df_reset

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
1,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
2,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True
3,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
4,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
796,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
797,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False
798,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False
799,440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False

In [ ]:
# 12
selected_columns = df[['Name', 'Type 1', 'HP']]
selected_columns

                      Name   Type 1  HP
0                Bulbasaur    Grass  45
1                  Ivysaur    Grass  60
2                 Venusaur    Grass  80
3    VenusaurMega Venusaur    Grass  80
4               Charmander     Fire  39
..                     ...      ...  ..
795                Diancie     Rock  50
796    DiancieMega Diancie     Rock  50
797    HoopaHoopa Confined  Psychic  80
798     HoopaHoopa Unbound  Psychic  80
799              Volcanion     Fire  80

[800 rows x 3 columns]

In [ ]:
# 13
grass_poison_pokemon = df[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison')]
grass_poison_pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,395,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
75,69,Bellsprout,Grass,Poison,300,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
344,315,Roselia,Grass,Poison,400,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,280,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,515,60,70,65,125,105,90,4,False
651,590,Foongus,Grass,Poison,294,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False

In [ ]:
# 14
legendary_hp_mean = df[df['Legendary'] == True]['HP'].mean()
legendary_hp_mean

92.73846153846154

In [ ]:
# 15
even_index_rows = df[df.index % 2 == 0]
even_index_rows

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
790,714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True

In [ ]:
# 16
even_index_rows.to_csv("filtered_pokemon.csv", index=False)

In [ ]:
# 17
selected_rows_and_columns = df.loc[:9, ['Name', 'Type 1', 'Attack']]
selected_rows_and_columns

                        Name Type 1  Attack
0                  Bulbasaur  Grass      49
1                    Ivysaur  Grass      62
2                   Venusaur  Grass      82
3      VenusaurMega Venusaur  Grass     100
4                 Charmander   Fire      52
5                 Charmeleon   Fire      64
6                  Charizard   Fire      84
7  CharizardMega Charizard X   Fire     130
8  CharizardMega Charizard Y   Fire     104
9                   Squirtle  Water      48

In [ ]:
# 18
max_defense = df['Defense'].max()
max_defense

230

In [ ]:
# 19
above_mean_speed = df[df['Speed'] > df['Speed'].mean()]
above_mean_speed

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [ ]:
# 20
selected_rows_and_columns = df.loc[:2, ['Name', 'Attack']]
selected_rows_and_columns

        Name  Attack
0  Bulbasaur      49
1    Ivysaur      62
2   Venusaur      82

In [ ]:
# 21
type_counts = df['Type 1'].value_counts()
type_counts

Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Dragon       32
Ground       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        17
Flying        4
Name: Type 1, dtype: int64

In [ ]:
# 22
gen_3_or_5_pokemon = df[(df['Generation'] == 3) | (df['Generation'] == 5)]
gen_3_or_5_pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
272,252,Treecko,Grass,NaN,310,40,45,35,65,55,70,3,False
273,253,Grovyle,Grass,NaN,405,50,65,45,85,65,95,3,False
274,254,Sceptile,Grass,NaN,530,70,85,65,105,85,120,3,False
275,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,False
276,255,Torchic,Fire,NaN,310,45,60,40,70,50,45,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
713,647,KeldeoOrdinary Forme,Water,Fighting,580,91,72,90,129,90,108,5,False
714,647,KeldeoResolute Forme,Water,Fighting,580,91,72,90,129,90,108,5,False
715,648,MeloettaAria Forme,Normal,Psychic,600,100,77,77,128,128,90,5,False
716,648,MeloettaPirouette Forme,Normal,Fighting,600,100,128,90,77,77,128,5,False
717,649,Genesect,Bug,Steel,600,71,120,95,120,95,99,5,False

In [ ]:
# 23
df.loc[df['Type 1']=='Fire', 'Type 1'] = 'Flame'
df.loc[df['Type 1']=='Flame'].head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Flame,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Flame,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Flame,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Flame,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Flame,Flying,634,78,104,78,159,115,100,1,False

In [ ]:
df.loc[df['Type 1']=='Flame', 'Type 1'] = 'Fire'

In [ ]:
# 24
p_starting_names = df[df['Name'].str.startswith('P')]
p_starting_names.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False

In [ ]:
# 25
type_attack_mean = df.groupby('Type 1')['Attack'].mean()
type_attack_mean

Type 1
Bug          70.971014
Dark         88.387097
Dragon      112.125000
Electric     69.090909
Fairy        61.529412
Fighting     96.777778
Fire         84.769231
Flying       78.750000
Ghost        73.781250
Grass        73.214286
Ground       95.750000
Ice          72.750000
Normal       73.469388
Poison       74.678571
Psychic      71.456140
Rock         92.863636
Steel        92.703704
Water        74.151786
Name: Attack, dtype: float64

In [ ]:
# 26
sorted_df = df.sort_values(by=['Type 1', 'Attack'], ascending=[True, False])
sorted_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
229,212,ScizorMega Scizor,Bug,Steel,600,70,150,140,65,100,75,2,False
650,589,Escavalier,Bug,Steel,495,70,135,105,60,105,20,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,370,Luvdisc,Water,NaN,330,43,30,55,40,65,97,3,False
198,183,Marill,Water,Fairy,250,70,20,50,20,50,40,2,False
508,458,Mantyke,Water,Flying,345,45,20,50,60,120,50,4,False
381,349,Feebas,Water,NaN,200,20,15,20,10,55,80,3,False
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False

In [ ]:
# 27
type_defense_median = df.groupby('Type 1')['Defense'].median()
type_defense_median

Type 1
Bug          60.0
Dark         70.0
Dragon       90.0
Electric     65.0
Fairy        66.0
Fighting     70.0
Fire         64.0
Flying       75.0
Ghost        72.5
Grass        66.0
Ground       84.5
Ice          75.0
Normal       60.0
Poison       67.0
Psychic      65.0
Rock        100.0
Steel       120.0
Water        70.0
Name: Defense, dtype: float64

In [ ]:
# 28
legendary_high_attack = df[(df['Legendary'] == True) & (df['Attack'] > 100)]
legendary_high_attack.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
162,150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True
263,244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True

In [ ]:
# 29
selected_columns_renamed = df.loc[:, ['Name', 'Total']].rename(columns={'Total': 'Overall'})
selected_columns_renamed

                      Name  Overall
0                Bulbasaur      318
1                  Ivysaur      405
2                 Venusaur      525
3    VenusaurMega Venusaur      625
4               Charmander      309
..                     ...      ...
795                Diancie      600
796    DiancieMega Diancie      700
797    HoopaHoopa Confined      600
798     HoopaHoopa Unbound      680
799              Volcanion      600

[800 rows x 2 columns]

In [ ]:
# 30
strong_water_pokemon = df[(df['Type 1'] == 'Water') & (df['Attack'] >= 80)]
strong_water_pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
60,55,Golduck,Water,NaN,500,80,82,78,95,80,85,1,False
67,62,Poliwrath,Water,Fighting,510,90,95,95,70,90,70,1,False
98,91,Cloyster,Water,Ice,525,50,95,180,85,45,70,1,False

In [ ]:
# 31
gen_4_defense = df[df['Generation'] == 4][['Name', 'Defense']]
gen_4_defense

                  Name  Defense
432            Turtwig       64
433             Grotle       85
434           Torterra      105
435           Chimchar       44
436           Monferno       52
..                 ...      ...
548            Manaphy      100
549            Darkrai       90
550  ShayminLand Forme      100
551   ShayminSky Forme       75
552             Arceus      120

[121 rows x 2 columns]

In [ ]:
# 32
type_combination_mean = df.groupby(['Type 1', 'Type 2'])['Total'].mean()
type_combination_mean

Type 1  Type 2
Bug     Electric    395.500000
        Fighting    550.000000
        Fire        455.000000
        Flying      419.500000
        Ghost       236.000000
                       ...
Water   Ice         511.666667
        Poison      426.666667
        Psychic     481.000000
        Rock        428.750000
        Steel       530.000000
Name: Total, Length: 136, dtype: float64

In [ ]:
# 33
mid_total_pokemon = df[(df['Total'] >= 400) & (df['Total'] <= 500)]
mid_total_pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
779,709,Trevenant,Ghost,Grass,474,85,110,76,65,82,56,6,False
784,711,GourgeistAverage Size,Ghost,Grass,494,65,90,122,58,75,84,6,False
785,711,GourgeistSmall Size,Ghost,Grass,494,55,85,122,58,75,99,6,False
786,711,GourgeistLarge Size,Ghost,Grass,494,75,95,122,58,75,69,6,False
787,711,GourgeistSuper Size,Ghost,Grass,494,85,100,122,58,75,54,6,False